stages:
  - build
  - test
  - deploy
  - pages

variables:
  MINIMAL_COVERAGE: 15

#
# BUILD
#

.build:linux:
  stage: build
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - |
      cmake .. \
      -DEXPRESSCPP_ENABLE_COVERAGE=ON \
      -DEXPRESSCPP_BUILD_EXAMPLE=ON \
      -DEXPRESSCPP_BUILD_TESTS=ON
    - make -j
    - |
      find . \
      -type f \
      -not \( -name 'test_expresscpp' -or -name '*.gcno' \) -delete
    - find . -type d -empty -delete
  tags:
    - docker
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/build/
    expire_in: 10 hrs

build:linux:gcc9:
  extends: .build:linux
  image: registry.gitlab.com/expresscpp/expresscpp/ci_gcc9:latest
  before_script:
    - export CC=/usr/bin/gcc-9
    - export CXX=/usr/bin/g++-9

# build:linux:clang8:
#   extends: .build:linux
#   image: registry.gitlab.com/expresscpp/expresscpp/ci:latest
#   before_script:
#     - export CC=/usr/bin/clang-9
#     - export CXX=/usr/bin/clang++-9

#
# TEST
#

.test:linux:
  stage: test
  image: registry.gitlab.com/expresscpp/expresscpp/ci:latest
  script:
    - ./build/bin/test_expresscpp --gtest_output=xml:./test_report.xml
    - |
      gcovr -r ${CI_PROJECT_DIR} \
      --gcov-executable gcov-9 \
      --exclude=".*test*." \
      --exclude=".*example*." \
      --exclude=".*/build/*." \
      --exclude=".*/_build/*." \
      --fail-under-line=$MINIMAL_COVERAGE
    - mkdir -p coverage/
    - |
      gcovr -r ${CI_PROJECT_DIR} \
      --gcov-executable gcov-9 \
      --exclude=".*test*." \
      --exclude=".*example*." \
      --exclude=".*/_build/*." \
      --exclude=".*/build/*." \
      -s -p --html --html-details \
      -o coverage/coverage.html
    - ls coverage/
    - mv ./coverage/coverage.html ./coverage/index.html || true
  tags:
    - docker
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/coverage/*  
    reports:
      junit: ${CI_PROJECT_DIR}/build/*.xml
    expire_in: 10 hrs

test:linux:gcc9:
  extends: .test:linux
  dependencies:
    - build:linux:gcc9
  needs: ["build:linux:gcc9"]

# test:linux:clang9:
#   extends: .test:linux
#   dependencies:
#     - build:linux:clang9
#   needs: ["build:linux:clang9"]

#
# DEPLOY
#

.package:
  stage: deploy
  image: registry.gitlab.com/expresscpp/expresscpp/ci_gcc9:latest
  before_script:
    - conan remote add expresscpp https://api.bintray.com/conan/expresscpp/expresscpp/
    - conan user -p $BINTRAY_API_KEY -r expresscpp gocarlos
    - apt update -y && apt install -y git
    - export CC=/usr/bin/gcc-9
    - export CXX=/usr/bin/g++-9
  tags:
    - docker

package_testing:
  extends: .package
  script:
    - conan create . expresscpp/testing --build missing
    - yes | conan upload expresscpp/* -r expresscpp || true
  only:
    - master

package_stable:
  extends: .package
  script:
    - conan create . expresscpp/stable --build missing
    - yes | conan upload expresscpp/* -r expresscpp || true
  tags:
    - docker
  only:
    - tags

pages:
  stage: pages
  image: ubuntu:19.04
  script:
    - mkdir -p public
    - mv ${CI_PROJECT_DIR}/coverage/* ${CI_PROJECT_DIR}/public/.
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/public
    expire_in: 1 hour
  only:
    refs:
      - master
  tags:
    - docker